# Generated by Django 3.0.6 on 2020-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
