# Generated by Django 3.0.6 on 2020-05-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='Blog.Category'),
        ),
    ]
